name: Multi-Platform Build and Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: amd64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build application
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o sleep-status-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Generate SHA256 checksum
        run: |
          sha256sum sleep-status-${{ matrix.goos }}-${{ matrix.goarch }} >> sha256.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sleep-status-${{ matrix.goos }}-${{ matrix.goarch }}
          path: sleep-status-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload SHA256 checksum
        uses: actions/upload-artifact@v2
        with:
          name: sha256-${{ matrix.goos }}-${{ matrix.goarch }}
          path: sha256.txt

  package:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: sleep-status-linux-amd64
          path: ./build
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: sleep-status-linux-arm64
          path: ./build
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: sleep-status-windows-amd64
          path: ./build
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: sleep-status-darwin-amd64
          path: ./build
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: sleep-status-darwin-arm64
          path: ./build

      - name: Download SHA256 checksums
        uses: actions/download-artifact@v2
        with:
          name: sha256-linux-amd64
          path: ./build
      - name: Download SHA256 checksums
        uses: actions/download-artifact@v2
        with:
          name: sha256-linux-arm64
          path: ./build
      - name: Download SHA256 checksums
        uses: actions/download-artifact@v2
        with:
          name: sha256-windows-amd64
          path: ./build
      - name: Download SHA256 checksums
        uses: actions/download-artifact@v2
        with:
          name: sha256-darwin-amd64
          path: ./build
      - name: Download SHA256 checksums
        uses: actions/download-artifact@v2
        with:
          name: sha256-darwin-arm64
          path: ./build

      - name: Create a tarball of the binaries
        run: |
          mkdir -p release
          tar -czvf release/sleep-status.tar.gz -C ./build .

      - name: Append SHA256 checksums
        run: |
          cat ./build/sha256*.txt > release/sha256.txt

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sleep-status-release
          path: release/
